name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: docker-compose build core
      - run: cd frontend
      - run: npm ci
      - run: npm run test-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        files: ./coverage/clover.xml
